version: '3'
services:
    zipkin:
        image: openzipkin/zipkin
        container_name: zipkin
        restart: always
        ports:
            - 9411:9411
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        restart: always
        ports:
            - 2181:2181
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=zookeeper
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        restart: always
        ports:
            - 9092:9092
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
            - KAFKA_ADVERTISED_PORT=9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        depends_on:
            - zookeeper
