server:
  port: 8302

spring:
  sleuth:
    integration:
      enabled: true
  zipkin:
    service:
      name: consumer-app
  cloud:
    stream:
      bindings:
        consumer-in-0:
          destination: sleuth
