server:
  port: 8302

spring:
  application:
    name: consumer-app
  sleuth:
    integration:
      enabled: true
  cloud:
    stream:
      bindings:
        consumer-in-0:
          destination: sleuth
