server:
  port: 8301

spring:
  application:
    name: producer-app
  sleuth:
    integration:
      enabled: true
  cloud:
    stream:
      bindings:
        output-out-0:
          destination: sleuth
