server:
  port: 8301

spring:
  sleuth:
    integration:
      enabled: true
  zipkin:
    service:
      name: producer-app
  cloud:
    stream:
      bindings:
        output-out-0:
          destination: sleuth
